package enums;

public enum ConfigProperties {

    BASE_URL,
    USERNAME,
    PASSWORD,
    OVERRIDE_REPORTS,
    PASSED_STEPS_SCREENSHOTS,
    FAILED_STEPS_SCREENSHOTS,
    SKIPPED_STEPS_SCREENSHOTS
}
