name: selenium experiment in-sprint testing
run-name: ${{ github.actor }} ran test suite in ${{ github.ref_name }}

on:
  push:
    branches:
      - feature/*

jobs:
  e2e-testsuite:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        browser: [ 'chrome', 'firefox' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Pull the project into the runner
        uses: actions/checkout@v4

      - name: Setting up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run the tests
        run: echo ./mvnw clean test -Dtests=us01-gestionar-vacantes-laborales -Dbrowser=${{matrix.browser}} -Dusername=${{secrets.USERNAME}} -Dpassword=${{secrets.PASSWORD}}

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test report on ${{ matrix.os }} ${{ matrix.browser }}
          path: ${{github.workspace}}/extent-test-output/index.html